import {
  AirtelIcon,
  BulkIcon,
  CakeIcon,
  CalendarIcon,
  DeleteIcon,
  DiscountIcon,
  EditIcon,
  ElipsisIcon,
  EventsIcon,
  GroupIcon,
  HomeIcon,
  InfoIcon,
  MessageIcon,
  MyAccountIcon,
  ReportsIcon,
  SearchIcon,
  SidebarLeftIcon,
  TicketIcon,
  UsersIcon,
  WalletIcon,
  WhatsAppIcon,
} from "@/public/icons";

export const iconRegistry = {
  home: HomeIcon,
  messages: MessageIcon,
  events: EventsIcon,
  reports: ReportsIcon,
  account: MyAccountIcon,
  sidebartrigger: SidebarLeftIcon,
  search: SearchIcon,
  ellipsis: ElipsisIcon,
  bulk: BulkIcon,
  whatsapp: WhatsAppIcon,
  calendar: CalendarIcon,
  wallet: WalletIcon,
  cake: CakeIcon,
  delete: DeleteIcon,
  edit: EditIcon,
  group: GroupIcon,
  users: UsersIcon,
  discount: DiscountIcon,
  ticket: TicketIcon,
  airtel: AirtelIcon,
  info: InfoIcon,
} as const;

export type IconKey = keyof typeof iconRegistry;
